<?php

Class Start extends Controller
{
    function __construct()
    {   
        parent::__construct();
        parent::__global();

        loader::base_helper('form');
    }                               

    public function index()
    {           
        loader::base_lib('calendar',false);
        
        $cal = calendar::instance();
        $cal->init();
        
        echo $cal->generate(2010, 10);    
        
        $this->title_tag = 'Welcome to Obullo Framework !';
    
        $this->head_tag  = css('welcome');
        $this->head_tag .= js('welcome');  
        
        $this->head_tag .= content::script('welcome'); 
        
        $data['sample_var'] = 'This page generated by Obullo Framework.';
        $this->body_tag  = content::view('view_welcome', $data);
    
        content::app_view('view_base_layout');
    }
    
} //end.
  
?>
